// <auto-generated />
using System;
using API_PROYECTO_ONG.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_PROYECTO_ONG.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251128163453_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API_PROYECTO_ONG.Models.Actividades", b =>
                {
                    b.Property<int>("idactividades")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idactividades"));

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("fecha_fin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fecha_inicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("nombre_Actividad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("proyecto_ONG_idproyecto_ONG")
                        .HasColumnType("int");

                    b.HasKey("idactividades");

                    b.HasIndex("proyecto_ONG_idproyecto_ONG");

                    b.ToTable("Actividades");
                });

            modelBuilder.Entity("API_PROYECTO_ONG.Models.Area", b =>
                {
                    b.Property<int>("idarea")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idarea"));

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("sede_idsede")
                        .HasColumnType("int");

                    b.HasKey("idarea");

                    b.HasIndex("sede_idsede");

                    b.ToTable("Areas");
                });

            modelBuilder.Entity("API_PROYECTO_ONG.Models.Capacitacion", b =>
                {
                    b.Property<int>("idcapacitacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idcapacitacion"));

                    b.Property<DateTime>("fecha_capacitacion")
                        .HasColumnType("datetime2");

                    b.HasKey("idcapacitacion");

                    b.ToTable("Capacitaciones");
                });

            modelBuilder.Entity("API_PROYECTO_ONG.Models.Contacto", b =>
                {
                    b.Property<int>("idContacto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idContacto"));

                    b.Property<string>("consultas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("numero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idContacto");

                    b.ToTable("Contactos");
                });

            modelBuilder.Entity("API_PROYECTO_ONG.Models.CuentaBancaria", b =>
                {
                    b.Property<int>("idcuentaBancaria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idcuentaBancaria"));

                    b.Property<string>("banco")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("numero_cta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("tipo_cuenta_idtipo_cuenta")
                        .HasColumnType("int");

                    b.HasKey("idcuentaBancaria");

                    b.HasIndex("tipo_cuenta_idtipo_cuenta");

                    b.ToTable("CuentasBancarias");
                });

            modelBuilder.Entity("API_PROYECTO_ONG.Models.Donacion", b =>
                {
                    b.Property<int>("iddonacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("iddonacion"));

                    b.Property<int?>("CuentaBancariaidcuentaBancaria")
                        .HasColumnType("int");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("donante_iddonante")
                        .HasColumnType("int");

                    b.Property<DateTime>("fecha_donacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("monto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("tipo_cuenta_idtipo_cuenta")
                        .HasColumnType("int");

                    b.Property<int>("voluntario_idvoluntario")
                        .HasColumnType("int");

                    b.HasKey("iddonacion");

                    b.HasIndex("CuentaBancariaidcuentaBancaria");

                    b.HasIndex("donante_iddonante");

                    b.HasIndex("tipo_cuenta_idtipo_cuenta");

                    b.HasIndex("voluntario_idvoluntario");

                    b.ToTable("Donaciones");
                });

            modelBuilder.Entity("API_PROYECTO_ONG.Models.Donante", b =>
                {
                    b.Property<int>("iddonante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("iddonante"));

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("tipo_donante_idtipo_donante")
                        .HasColumnType("int");

                    b.HasKey("iddonante");

                    b.HasIndex("tipo_donante_idtipo_donante");

                    b.ToTable("Donantes");
                });

            modelBuilder.Entity("API_PROYECTO_ONG.Models.Empleado", b =>
                {
                    b.Property<int>("idempleado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idempleado"));

                    b.Property<int>("Persona_idPersona")
                        .HasColumnType("int");

                    b.Property<string>("cargo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("fecha_contratacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("salario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idempleado");

                    b.HasIndex("Persona_idPersona");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("API_PROYECTO_ONG.Models.Evento", b =>
                {
                    b.Property<int>("idEvento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idEvento"));

                    b.Property<string>("descripcionEvento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("fechaFin_evento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fechaInicio_evento")
                        .HasColumnType("datetime2");

                    b.Property<string>("lugar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombreEvento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("proyecto_ONG_idproyecto_ONG")
                        .HasColumnType("int");

                    b.HasKey("idEvento");

                    b.HasIndex("proyecto_ONG_idproyecto_ONG");

                    b.ToTable("Eventos");
                });

            modelBuilder.Entity("API_PROYECTO_ONG.Models.Factura", b =>
                {
                    b.Property<int>("idfactura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idfactura"));

                    b.Property<string>("donador_proveedor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("fecha_emision")
                        .HasColumnType("datetime2");

                    b.Property<int>("gasto_idgasto")
                        .HasColumnType("int");

                    b.Property<int>("metodo_pago_idmetodo_pago")
                        .HasColumnType("int");

                    b.Property<string>("monto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("numero_factura")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idfactura");

                    b.HasIndex("gasto_idgasto");

                    b.HasIndex("metodo_pago_idmetodo_pago");

                    b.ToTable("Facturas");
                });

            modelBuilder.Entity("API_PROYECTO_ONG.Models.Gasto", b =>
                {
                    b.Property<int>("idgasto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idgasto"));

                    b.Property<DateTime>("fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("monto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("tipo_gasto_idtipo_gasto")
                        .HasColumnType("int");

                    b.HasKey("idgasto");

                    b.HasIndex("tipo_gasto_idtipo_gasto");

                    b.ToTable("Gastos");
                });

            modelBuilder.Entity("API_PROYECTO_ONG.Models.MetodoPago", b =>
                {
                    b.Property<int>("idmetodo_pago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idmetodo_pago"));

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idmetodo_pago");

                    b.ToTable("MetodosPago");
                });

            modelBuilder.Entity("API_PROYECTO_ONG.Models.Noticias", b =>
                {
                    b.Property<int>("idNoticias")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idNoticias"));

                    b.Property<string>("autor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("fechaPublicacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("informacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idNoticias");

                    b.ToTable("Noticias");
                });

            modelBuilder.Entity("API_PROYECTO_ONG.Models.Noticias_has_area", b =>
                {
                    b.Property<int>("Noticias_idNoticias")
                        .HasColumnType("int");

                    b.Property<int>("area_idarea")
                        .HasColumnType("int");

                    b.HasKey("Noticias_idNoticias", "area_idarea");

                    b.HasIndex("area_idarea");

                    b.ToTable("NoticiasAreas");
                });

            modelBuilder.Entity("API_PROYECTO_ONG.Models.ODS", b =>
                {
                    b.Property<int>("idODS")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idODS"));

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre_ODS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idODS");

                    b.ToTable("ODS");
                });

            modelBuilder.Entity("API_PROYECTO_ONG.Models.ONG", b =>
                {
                    b.Property<int>("idONG")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idONG"));

                    b.Property<string>("correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fecha_Creacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mision")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre_ONG")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("vision")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idONG");

                    b.ToTable("ONGs");
                });

            modelBuilder.Entity("API_PROYECTO_ONG.Models.Pais", b =>
                {
                    b.Property<int>("idpais")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idpais"));

                    b.Property<string>("nombrePais")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("region")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idpais");

                    b.ToTable("Paises");
                });

            modelBuilder.Entity("API_PROYECTO_ONG.Models.Persona", b =>
                {
                    b.Property<int>("idPersona")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idPersona"));

                    b.Property<string>("P_apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("S_apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("S_nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("fecha_nac")
                        .HasColumnType("datetime2");

                    b.HasKey("idPersona");

                    b.ToTable("Personas");
                });

            modelBuilder.Entity("API_PROYECTO_ONG.Models.Presupuesto", b =>
                {
                    b.Property<int>("idpresupuesto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idpresupuesto"));

                    b.Property<string>("monto_asignado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("monto_usado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idpresupuesto");

                    b.ToTable("Presupuestos");
                });

            modelBuilder.Entity("API_PROYECTO_ONG.Models.ProyectoEmpleado", b =>
                {
                    b.Property<int>("idproyecto_empleado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idproyecto_empleado"));

                    b.Property<int>("idempleado")
                        .HasColumnType("int");

                    b.HasKey("idproyecto_empleado");

                    b.HasIndex("idempleado");

                    b.ToTable("ProyectoEmpleados");
                });

            modelBuilder.Entity("API_PROYECTO_ONG.Models.ProyectoONG_has_ODS", b =>
                {
                    b.Property<int>("proyecto_ONG_idproyecto_ONG")
                        .HasColumnType("int");

                    b.Property<int>("ODS_idODS")
                        .HasColumnType("int");

                    b.HasKey("proyecto_ONG_idproyecto_ONG", "ODS_idODS");

                    b.HasIndex("ODS_idODS");

                    b.ToTable("ProyectoODS");
                });

            modelBuilder.Entity("API_PROYECTO_ONG.Models.ProyectoONG_has_Pais", b =>
                {
                    b.Property<int>("proyecto_ONG_idproyecto_ONG")
                        .HasColumnType("int");

                    b.Property<int>("pais_idpais")
                        .HasColumnType("int");

                    b.HasKey("proyecto_ONG_idproyecto_ONG", "pais_idpais");

                    b.HasIndex("pais_idpais");

                    b.ToTable("ProyectoPaises");
                });

            modelBuilder.Entity("API_PROYECTO_ONG.Models.ProyectoVoluntario", b =>
                {
                    b.Property<int>("idproyecto_voluntario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idproyecto_voluntario"));

                    b.Property<int>("idvoluntario")
                        .HasColumnType("int");

                    b.HasKey("idproyecto_voluntario");

                    b.HasIndex("idvoluntario");

                    b.ToTable("ProyectoVoluntarios");
                });

            modelBuilder.Entity("API_PROYECTO_ONG.Models.Proyecto_ONG", b =>
                {
                    b.Property<int>("idproyecto_ONG")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idproyecto_ONG"));

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fecha_fin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("fecha_inicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("nombre_proyecto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("presupuesto_otorgado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idproyecto_ONG");

                    b.ToTable("ProyectosONG");
                });

            modelBuilder.Entity("API_PROYECTO_ONG.Models.Proyecto_ONG_has_proyecto_empleado", b =>
                {
                    b.Property<int>("proyecto_ONG_idproyecto_ONG")
                        .HasColumnType("int");

                    b.Property<int>("proyecto_empleado_idproyecto_empleado")
                        .HasColumnType("int");

                    b.HasKey("proyecto_ONG_idproyecto_ONG", "proyecto_empleado_idproyecto_empleado");

                    b.HasIndex("proyecto_empleado_idproyecto_empleado");

                    b.ToTable("ProyectoONGEmpleados");
                });

            modelBuilder.Entity("API_PROYECTO_ONG.Models.Proyecto_ONG_has_proyecto_voluntario", b =>
                {
                    b.Property<int>("proyecto_ONG_idproyecto_ONG")
                        .HasColumnType("int");

                    b.Property<int>("proyecto_voluntario_idproyecto_voluntario")
                        .HasColumnType("int");

                    b.HasKey("proyecto_ONG_idproyecto_ONG", "proyecto_voluntario_idproyecto_voluntario");

                    b.HasIndex("proyecto_voluntario_idproyecto_voluntario");

                    b.ToTable("ProyectoONGVoluntarios");
                });

            modelBuilder.Entity("API_PROYECTO_ONG.Models.Rol", b =>
                {
                    b.Property<int>("idrol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idrol"));

                    b.Property<string>("nombre_rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idrol");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("API_PROYECTO_ONG.Models.RolUsuario", b =>
                {
                    b.Property<int>("idrol")
                        .HasColumnType("int");

                    b.Property<int>("usuario_idusuario")
                        .HasColumnType("int");

                    b.Property<string>("descripcion_rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idrol", "usuario_idusuario");

                    b.HasIndex("usuario_idusuario");

                    b.ToTable("RolUsuarios");
                });

            modelBuilder.Entity("API_PROYECTO_ONG.Models.Sede", b =>
                {
                    b.Property<int>("idsede")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idsede"));

                    b.Property<int>("ONG_idONG")
                        .HasColumnType("int");

                    b.Property<string>("direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("responsable")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idsede");

                    b.HasIndex("ONG_idONG");

                    b.ToTable("Sedes");
                });

            modelBuilder.Entity("API_PROYECTO_ONG.Models.Telefono", b =>
                {
                    b.Property<int>("idtelefono")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idtelefono"));

                    b.Property<int>("Persona_idPersona")
                        .HasColumnType("int");

                    b.Property<string>("numero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idtelefono");

                    b.HasIndex("Persona_idPersona");

                    b.ToTable("Telefonos");
                });

            modelBuilder.Entity("API_PROYECTO_ONG.Models.TipoCuenta", b =>
                {
                    b.Property<int>("idtipo_cuenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idtipo_cuenta"));

                    b.Property<string>("descripcion_cuenta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idtipo_cuenta");

                    b.ToTable("TiposCuenta");
                });

            modelBuilder.Entity("API_PROYECTO_ONG.Models.TipoDonante", b =>
                {
                    b.Property<int>("idtipo_donante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idtipo_donante"));

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idtipo_donante");

                    b.ToTable("TiposDonante");
                });

            modelBuilder.Entity("API_PROYECTO_ONG.Models.TipoGasto", b =>
                {
                    b.Property<int>("idtipo_gasto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idtipo_gasto"));

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idtipo_gasto");

                    b.ToTable("TiposGasto");
                });

            modelBuilder.Entity("API_PROYECTO_ONG.Models.TipoTransaccion", b =>
                {
                    b.Property<int>("idtipo_transaccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idtipo_transaccion"));

                    b.Property<string>("descripcion_transaccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idtipo_transaccion");

                    b.ToTable("TiposTransaccion");
                });

            modelBuilder.Entity("API_PROYECTO_ONG.Models.Transaccion", b =>
                {
                    b.Property<int>("idtransaccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idtransaccion"));

                    b.Property<int>("donacion_iddonacion")
                        .HasColumnType("int");

                    b.Property<DateTime>("fecha_transaccion")
                        .HasColumnType("datetime2");

                    b.Property<int>("gasto_idgasto")
                        .HasColumnType("int");

                    b.Property<int>("tipo_transaccion_idtipo_transaccion")
                        .HasColumnType("int");

                    b.HasKey("idtransaccion");

                    b.HasIndex("donacion_iddonacion");

                    b.HasIndex("gasto_idgasto");

                    b.HasIndex("tipo_transaccion_idtipo_transaccion");

                    b.ToTable("Transacciones");
                });

            modelBuilder.Entity("API_PROYECTO_ONG.Models.Usuario", b =>
                {
                    b.Property<int>("idusuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idusuario"));

                    b.Property<int>("ONG_idONG")
                        .HasColumnType("int");

                    b.Property<string>("contrasena")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("empleado_idempleado")
                        .HasColumnType("int");

                    b.Property<string>("nombre_usuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idusuario");

                    b.HasIndex("ONG_idONG");

                    b.HasIndex("empleado_idempleado");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("API_PROYECTO_ONG.Models.Voluntario", b =>
                {
                    b.Property<int>("idvoluntario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idvoluntario"));

                    b.Property<int>("Persona_idPersona")
                        .HasColumnType("int");

                    b.Property<string>("disponibilidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idvoluntario");

                    b.HasIndex("Persona_idPersona");

                    b.ToTable("Voluntarios");
                });

            modelBuilder.Entity("API_PROYECTO_ONG.Models.VoluntarioCapacitacion", b =>
                {
                    b.Property<int>("voluntario_idvoluntario")
                        .HasColumnType("int");

                    b.Property<int>("capacitacion_idcapacitacion")
                        .HasColumnType("int");

                    b.Property<string>("tema_capacitacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("voluntario_idvoluntario", "capacitacion_idcapacitacion");

                    b.HasIndex("capacitacion_idcapacitacion");

                    b.ToTable("VoluntarioCapacitaciones");
                });

            modelBuilder.Entity("API_PROYECTO_ONG.Models.Actividades", b =>
                {
                    b.HasOne("API_PROYECTO_ONG.Models.Proyecto_ONG", "Proyecto")
                        .WithMany("Actividades")
                        .HasForeignKey("proyecto_ONG_idproyecto_ONG")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proyecto");
                });

            modelBuilder.Entity("API_PROYECTO_ONG.Models.Area", b =>
                {
                    b.HasOne("API_PROYECTO_ONG.Models.Sede", "Sede")
                        .WithMany("Areas")
                        .HasForeignKey("sede_idsede")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sede");
                });

            modelBuilder.Entity("API_PROYECTO_ONG.Models.CuentaBancaria", b =>
                {
                    b.HasOne("API_PROYECTO_ONG.Models.TipoCuenta", "TipoCuenta")
                        .WithMany("Cuentas")
                        .HasForeignKey("tipo_cuenta_idtipo_cuenta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoCuenta");
                });

            modelBuilder.Entity("API_PROYECTO_ONG.Models.Donacion", b =>
                {
                    b.HasOne("API_PROYECTO_ONG.Models.CuentaBancaria", null)
                        .WithMany("Donaciones")
                        .HasForeignKey("CuentaBancariaidcuentaBancaria");

                    b.HasOne("API_PROYECTO_ONG.Models.Donante", "Donante")
                        .WithMany("Donaciones")
                        .HasForeignKey("donante_iddonante")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_PROYECTO_ONG.Models.TipoCuenta", "TipoCuenta")
                        .WithMany("Donaciones")
                        .HasForeignKey("tipo_cuenta_idtipo_cuenta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_PROYECTO_ONG.Models.Voluntario", "Voluntario")
                        .WithMany("Donaciones")
                        .HasForeignKey("voluntario_idvoluntario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Donante");

                    b.Navigation("TipoCuenta");

                    b.Navigation("Voluntario");
                });

            modelBuilder.Entity("API_PROYECTO_ONG.Models.Donante", b =>
                {
                    b.HasOne("API_PROYECTO_ONG.Models.TipoDonante", "TipoDonante")
                        .WithMany("Donantes")
                        .HasForeignKey("tipo_donante_idtipo_donante")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoDonante");
                });

            modelBuilder.Entity("API_PROYECTO_ONG.Models.Empleado", b =>
                {
                    b.HasOne("API_PROYECTO_ONG.Models.Persona", "Persona")
                        .WithMany("Empleados")
                        .HasForeignKey("Persona_idPersona")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("API_PROYECTO_ONG.Models.Evento", b =>
                {
                    b.HasOne("API_PROYECTO_ONG.Models.Proyecto_ONG", "Proyecto")
                        .WithMany("Eventos")
                        .HasForeignKey("proyecto_ONG_idproyecto_ONG")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proyecto");
                });

            modelBuilder.Entity("API_PROYECTO_ONG.Models.Factura", b =>
                {
                    b.HasOne("API_PROYECTO_ONG.Models.Gasto", "Gasto")
                        .WithMany("Facturas")
                        .HasForeignKey("gasto_idgasto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_PROYECTO_ONG.Models.MetodoPago", "MetodoPago")
                        .WithMany("Facturas")
                        .HasForeignKey("metodo_pago_idmetodo_pago")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gasto");

                    b.Navigation("MetodoPago");
                });

            modelBuilder.Entity("API_PROYECTO_ONG.Models.Gasto", b =>
                {
                    b.HasOne("API_PROYECTO_ONG.Models.TipoGasto", "TipoGasto")
                        .WithMany("Gastos")
                        .HasForeignKey("tipo_gasto_idtipo_gasto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoGasto");
                });

            modelBuilder.Entity("API_PROYECTO_ONG.Models.Noticias_has_area", b =>
                {
                    b.HasOne("API_PROYECTO_ONG.Models.Noticias", "Noticias")
                        .WithMany("Areas")
                        .HasForeignKey("Noticias_idNoticias")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_PROYECTO_ONG.Models.Area", "Area")
                        .WithMany("Noticias")
                        .HasForeignKey("area_idarea")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("Noticias");
                });

            modelBuilder.Entity("API_PROYECTO_ONG.Models.ProyectoEmpleado", b =>
                {
                    b.HasOne("API_PROYECTO_ONG.Models.Empleado", "Empleado")
                        .WithMany("ProyectoEmpleados")
                        .HasForeignKey("idempleado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("API_PROYECTO_ONG.Models.ProyectoONG_has_ODS", b =>
                {
                    b.HasOne("API_PROYECTO_ONG.Models.ODS", "ODS")
                        .WithMany("ProyectoODS")
                        .HasForeignKey("ODS_idODS")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_PROYECTO_ONG.Models.Proyecto_ONG", "Proyecto")
                        .WithMany("ODS")
                        .HasForeignKey("proyecto_ONG_idproyecto_ONG")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ODS");

                    b.Navigation("Proyecto");
                });

            modelBuilder.Entity("API_PROYECTO_ONG.Models.ProyectoONG_has_Pais", b =>
                {
                    b.HasOne("API_PROYECTO_ONG.Models.Pais", "Pais")
                        .WithMany("ProyectoPais")
                        .HasForeignKey("pais_idpais")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_PROYECTO_ONG.Models.Proyecto_ONG", "Proyecto")
                        .WithMany("Paises")
                        .HasForeignKey("proyecto_ONG_idproyecto_ONG")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pais");

                    b.Navigation("Proyecto");
                });

            modelBuilder.Entity("API_PROYECTO_ONG.Models.ProyectoVoluntario", b =>
                {
                    b.HasOne("API_PROYECTO_ONG.Models.Voluntario", "Voluntario")
                        .WithMany("ProyectoVoluntarios")
                        .HasForeignKey("idvoluntario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Voluntario");
                });

            modelBuilder.Entity("API_PROYECTO_ONG.Models.Proyecto_ONG_has_proyecto_empleado", b =>
                {
                    b.HasOne("API_PROYECTO_ONG.Models.Proyecto_ONG", "Proyecto")
                        .WithMany("ProyectoEmpleados")
                        .HasForeignKey("proyecto_ONG_idproyecto_ONG")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_PROYECTO_ONG.Models.ProyectoEmpleado", "ProyectoEmpleado")
                        .WithMany("Proyectos")
                        .HasForeignKey("proyecto_empleado_idproyecto_empleado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proyecto");

                    b.Navigation("ProyectoEmpleado");
                });

            modelBuilder.Entity("API_PROYECTO_ONG.Models.Proyecto_ONG_has_proyecto_voluntario", b =>
                {
                    b.HasOne("API_PROYECTO_ONG.Models.Proyecto_ONG", "Proyecto")
                        .WithMany("ProyectoVoluntarios")
                        .HasForeignKey("proyecto_ONG_idproyecto_ONG")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_PROYECTO_ONG.Models.ProyectoVoluntario", "ProyectoVoluntario")
                        .WithMany("Proyectos")
                        .HasForeignKey("proyecto_voluntario_idproyecto_voluntario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proyecto");

                    b.Navigation("ProyectoVoluntario");
                });

            modelBuilder.Entity("API_PROYECTO_ONG.Models.RolUsuario", b =>
                {
                    b.HasOne("API_PROYECTO_ONG.Models.Rol", "Rol")
                        .WithMany("RolUsuarios")
                        .HasForeignKey("idrol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_PROYECTO_ONG.Models.Usuario", "Usuario")
                        .WithMany("Roles")
                        .HasForeignKey("usuario_idusuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("API_PROYECTO_ONG.Models.Sede", b =>
                {
                    b.HasOne("API_PROYECTO_ONG.Models.ONG", "ONG")
                        .WithMany("Sedes")
                        .HasForeignKey("ONG_idONG")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ONG");
                });

            modelBuilder.Entity("API_PROYECTO_ONG.Models.Telefono", b =>
                {
                    b.HasOne("API_PROYECTO_ONG.Models.Persona", "Persona")
                        .WithMany("Telefonos")
                        .HasForeignKey("Persona_idPersona")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("API_PROYECTO_ONG.Models.Transaccion", b =>
                {
                    b.HasOne("API_PROYECTO_ONG.Models.Donacion", "Donacion")
                        .WithMany("Transacciones")
                        .HasForeignKey("donacion_iddonacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_PROYECTO_ONG.Models.Gasto", "Gasto")
                        .WithMany("Transacciones")
                        .HasForeignKey("gasto_idgasto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_PROYECTO_ONG.Models.TipoTransaccion", "TipoTransaccion")
                        .WithMany("Transacciones")
                        .HasForeignKey("tipo_transaccion_idtipo_transaccion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Donacion");

                    b.Navigation("Gasto");

                    b.Navigation("TipoTransaccion");
                });

            modelBuilder.Entity("API_PROYECTO_ONG.Models.Usuario", b =>
                {
                    b.HasOne("API_PROYECTO_ONG.Models.ONG", "ONG")
                        .WithMany("Usuarios")
                        .HasForeignKey("ONG_idONG")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_PROYECTO_ONG.Models.Empleado", "Empleado")
                        .WithMany("Usuarios")
                        .HasForeignKey("empleado_idempleado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");

                    b.Navigation("ONG");
                });

            modelBuilder.Entity("API_PROYECTO_ONG.Models.Voluntario", b =>
                {
                    b.HasOne("API_PROYECTO_ONG.Models.Persona", "Persona")
                        .WithMany("Voluntarios")
                        .HasForeignKey("Persona_idPersona")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("API_PROYECTO_ONG.Models.VoluntarioCapacitacion", b =>
                {
                    b.HasOne("API_PROYECTO_ONG.Models.Capacitacion", "Capacitacion")
                        .WithMany("Voluntarios")
                        .HasForeignKey("capacitacion_idcapacitacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_PROYECTO_ONG.Models.Voluntario", "Voluntario")
                        .WithMany("Capacitaciones")
                        .HasForeignKey("voluntario_idvoluntario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Capacitacion");

                    b.Navigation("Voluntario");
                });

            modelBuilder.Entity("API_PROYECTO_ONG.Models.Area", b =>
                {
                    b.Navigation("Noticias");
                });

            modelBuilder.Entity("API_PROYECTO_ONG.Models.Capacitacion", b =>
                {
                    b.Navigation("Voluntarios");
                });

            modelBuilder.Entity("API_PROYECTO_ONG.Models.CuentaBancaria", b =>
                {
                    b.Navigation("Donaciones");
                });

            modelBuilder.Entity("API_PROYECTO_ONG.Models.Donacion", b =>
                {
                    b.Navigation("Transacciones");
                });

            modelBuilder.Entity("API_PROYECTO_ONG.Models.Donante", b =>
                {
                    b.Navigation("Donaciones");
                });

            modelBuilder.Entity("API_PROYECTO_ONG.Models.Empleado", b =>
                {
                    b.Navigation("ProyectoEmpleados");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("API_PROYECTO_ONG.Models.Gasto", b =>
                {
                    b.Navigation("Facturas");

                    b.Navigation("Transacciones");
                });

            modelBuilder.Entity("API_PROYECTO_ONG.Models.MetodoPago", b =>
                {
                    b.Navigation("Facturas");
                });

            modelBuilder.Entity("API_PROYECTO_ONG.Models.Noticias", b =>
                {
                    b.Navigation("Areas");
                });

            modelBuilder.Entity("API_PROYECTO_ONG.Models.ODS", b =>
                {
                    b.Navigation("ProyectoODS");
                });

            modelBuilder.Entity("API_PROYECTO_ONG.Models.ONG", b =>
                {
                    b.Navigation("Sedes");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("API_PROYECTO_ONG.Models.Pais", b =>
                {
                    b.Navigation("ProyectoPais");
                });

            modelBuilder.Entity("API_PROYECTO_ONG.Models.Persona", b =>
                {
                    b.Navigation("Empleados");

                    b.Navigation("Telefonos");

                    b.Navigation("Voluntarios");
                });

            modelBuilder.Entity("API_PROYECTO_ONG.Models.ProyectoEmpleado", b =>
                {
                    b.Navigation("Proyectos");
                });

            modelBuilder.Entity("API_PROYECTO_ONG.Models.ProyectoVoluntario", b =>
                {
                    b.Navigation("Proyectos");
                });

            modelBuilder.Entity("API_PROYECTO_ONG.Models.Proyecto_ONG", b =>
                {
                    b.Navigation("Actividades");

                    b.Navigation("Eventos");

                    b.Navigation("ODS");

                    b.Navigation("Paises");

                    b.Navigation("ProyectoEmpleados");

                    b.Navigation("ProyectoVoluntarios");
                });

            modelBuilder.Entity("API_PROYECTO_ONG.Models.Rol", b =>
                {
                    b.Navigation("RolUsuarios");
                });

            modelBuilder.Entity("API_PROYECTO_ONG.Models.Sede", b =>
                {
                    b.Navigation("Areas");
                });

            modelBuilder.Entity("API_PROYECTO_ONG.Models.TipoCuenta", b =>
                {
                    b.Navigation("Cuentas");

                    b.Navigation("Donaciones");
                });

            modelBuilder.Entity("API_PROYECTO_ONG.Models.TipoDonante", b =>
                {
                    b.Navigation("Donantes");
                });

            modelBuilder.Entity("API_PROYECTO_ONG.Models.TipoGasto", b =>
                {
                    b.Navigation("Gastos");
                });

            modelBuilder.Entity("API_PROYECTO_ONG.Models.TipoTransaccion", b =>
                {
                    b.Navigation("Transacciones");
                });

            modelBuilder.Entity("API_PROYECTO_ONG.Models.Usuario", b =>
                {
                    b.Navigation("Roles");
                });

            modelBuilder.Entity("API_PROYECTO_ONG.Models.Voluntario", b =>
                {
                    b.Navigation("Capacitaciones");

                    b.Navigation("Donaciones");

                    b.Navigation("ProyectoVoluntarios");
                });
#pragma warning restore 612, 618
        }
    }
}
